/**
 * Every tunable number in the game, in one file.
 *
 * Scuttle's quality is a tuning problem rather than a feature problem — step
 * duration, lateral speed, lane speeds and gap sizes are what decide whether
 * the sideways asymmetry reads as a tactic or as an annoyance. Keeping them
 * together means a tuning pass is one file open, and means nothing in the
 * simulation can quietly hard-code a number that a later pass will not find.
 *
 * Distances are in board units. The board is {@link BOARD_WIDTH} units across
 * and the renderer scales that to whatever the screen is, so these numbers are
 * device-independent by construction.
 */

/**
 * Simulation ticks per second.
 *
 * The simulation advances in whole ticks and never sees a frame delta, so this
 * is the only rate that affects play. Render rate is a separate concern and
 * changing it cannot change a run.
 */
export const TICK_HZ = 60;

/** Seconds per simulation tick. */
export const DT = 1 / TICK_HZ;

/** Milliseconds per simulation tick. */
export const TICK_MS = 1000 / TICK_HZ;

/**
 * Longest frame the loop will pay back in one go, in milliseconds.
 *
 * A backgrounded tab or a stalled main thread produces a delta measured in
 * seconds. Without a clamp the loop tries to catch up in a single frame, which
 * takes longer than a frame, which makes the next delta bigger still. Dropping
 * the excess costs the player some elapsed board time and keeps the tab alive.
 */
export const MAX_FRAME_MS = 250;

/** Width of the playable board, in board units. */
export const BOARD_WIDTH = 120;

/** Height of one lane, in board units. */
export const LANE_HEIGHT = 16;

/**
 * How many lanes are on screen at once.
 *
 * Fixed rather than derived from the viewport: a taller phone seeing further
 * down the beach would be playing an easier version of the same run. Eleven is
 * chosen so a phone held in portrait letterboxes by only a few dozen pixels,
 * while a wide window letterboxes at the sides rather than showing more beach.
 */
export const VISIBLE_LANES = 11;

/** How many lanes of already-crossed beach stay visible below the crab. */
export const LANES_BEHIND = 2;

/**
 * Half the crab's width, in board units.
 *
 * Wider than it is tall, so the shape says which way the thing is built to move
 * before the player has pressed anything.
 */
export const PLAYER_HALF_W = 6.5;

/** Half the crab's height, in board units. */
export const PLAYER_HALF_H = 4.5;

/**
 * Lateral speed in board units per second.
 *
 * Crossing the whole board takes a little over two and a half seconds, and one
 * forward step's worth of time buys roughly one and a half hazard gaps of
 * sideways travel — enough that sliding to a better entry point is a real
 * choice rather than a rounding error.
 */
export const LATERAL_SPEED = 46;

/**
 * Ticks a forward step takes, start to finish.
 *
 * Once begun the step runs to completion and refuses all input, so this number
 * is the length of the commitment the player is making.
 */
export const STEP_TICKS = 24;

/**
 * How long a forward press stays live after arriving mid-step.
 *
 * Short enough that a press made early in a step is simply missed, long enough
 * that chaining two crossings does not need a tick-perfect tap.
 */
export const STEP_BUFFER_TICKS = 8;

/** Half the height of a hazard, in board units. */
export const HAZARD_HALF_H = 5.5;

/**
 * How far past each edge of the board a drifting lane extends.
 *
 * Hazards wrap at the ends of this margin rather than at the board edge, so a
 * hazard is always fully off-board at the moment it wraps and can never appear
 * to teleport through the crab. It has to exceed the widest hazard.
 */
export const WRAP_MARGIN = 40;

/** Total cycle length of a drifting lane, in board units. */
export const CYCLE_SPAN = BOARD_WIDTH + 2 * WRAP_MARGIN;

/**
 * Narrowest gap the generator will ever leave between two hazards.
 *
 * Every lane is built by giving each gap this much first and only then sharing
 * out what is left, so a lane that cannot be crossed is not something the seed
 * is capable of producing, whatever the day's numbers come out as.
 *
 * A drifting gap has to be wide enough to survive the crossing, not merely to
 * hold the crab. The step cannot be steered, so from the moment it begins the
 * gap slides on underneath a crab that cannot follow it: at the fastest lane
 * speed that is most of ten units of travel gone before it lands. Sizing this
 * to the crab alone leaves a lane that looks passable and arithmetically is
 * not, which reads to a player as the game cheating.
 *
 * A still gap has no such problem and only has to be wide enough to stand in
 * with room to line up first.
 */
export const MIN_GAP = { drift: 32, still: 24 } as const;

/** Every fourth lane is safe, giving a rhythm of three crossings and a breath. */
export const SAFE_LANE_INTERVAL = 4;

/**
 * How many lanes the beach takes to reach full difficulty.
 *
 * Without this every row is generated by identical rules, so the second lane of
 * the run is drawn from the same distribution as the twenty-ninth — and since a
 * player attempts the opening on every single run and the far end of the beach
 * perhaps once, an average lane placed at row two reads as a brutal one. The
 * beach has to introduce itself.
 *
 * Short on purpose. This is a ramp, not a tutorial: the first block of lanes is
 * gentler and the beach is at full strength by the second, which is early
 * enough that most of the run is still the game it was. Lengthening this would
 * flatten the whole beach rather than easing its opening.
 */
export const RAMP_LANES = 8;

/**
 * How many lanes of beach lie between the promenade and the sea.
 *
 * The beach is the same length every day — only what is in it varies. A
 * generated length would make two days' times incomparable and a personal best
 * meaningless, and it would turn "did you beat it" from a fact everybody shares
 * into a question about which beach you happened to get.
 *
 * A multiple of {@link SAFE_LANE_INTERVAL} so the last thing before the water
 * is a safe lane rather than a hazard the player is forced to gamble on with
 * the whole run behind them.
 *
 * This number is a first guess and is meant to be moved. It is the run's
 * length, and the run's length cannot be reasoned about — only played.
 */
export const BEACH_LANES = 32;

/** The row the sea begins at. Reaching it wins the day. */
export const SEA_ROW = BEACH_LANES + 1;

/**
 * How many lanes of surf there are at dead low tide and at full high tide.
 *
 * The tide's whole visible effect is this number growing. The surf's leading
 * edge starts three lanes from the sea and advances to nine, and the wet sand
 * of the tide line is whatever is left between the surf and the dry sand — six
 * lanes of breather at the start of a run and none at all by the end of one.
 *
 * The maximum is a floor on the dry sand as much as a ceiling on the water. The
 * tide is not allowed to dissolve a seeded dry-sand lane: those lanes are what
 * the day's seed actually decides, and water arriving under a crab mid-step
 * would delete a hazard it had already committed to crossing.
 */
export const SURF_LANES = { low: 3, high: 9 } as const;

/** The last row of dry sand. The tide never reaches past it. */
export const DRY_LANES = BEACH_LANES - SURF_LANES.high;

/**
 * Ticks for the tide to come fully in.
 *
 * Seventy-five seconds against a confident run of roughly twenty-five means a
 * player who reads the beach well meets perhaps a third of the tide, and one
 * who hesitates on every lane arrives at the water with no wet sand left to
 * rest on. That is the escalation doing its job: the cost of caution is the
 * board getting worse, not a number going up.
 *
 * The most provisional constant in the file. If the tide runs too fast the game
 * stops being about reading lanes and starts being about rushing them, which is
 * the opposite of what a committed forward step is for.
 */
export const TIDE_FULL_TICKS = 75 * TICK_HZ;

/**
 * Ticks in one full wave cycle, and how many of them a lane spends washing.
 *
 * Roughly a third of the cycle is water, so a surf lane is crossable more often
 * than not and the problem is timing rather than patience.
 */
export const SURF_PERIOD_TICKS = 150;

/** Ticks a surf lane spends washing, out of {@link SURF_PERIOD_TICKS}. */
export const SURF_BREAK_TICKS = 48;

/**
 * Ticks of delay between one surf lane breaking and the next one down.
 *
 * Non-zero so a set reads as a wave rolling in rather than as the whole band
 * blinking at once. Lanes nearer the sea break first, so the motion runs
 * shoreward, which is the direction the water is actually going.
 */
export const SURF_ROW_LAG = 26;

/**
 * Ticks of immunity a crab keeps after a wave sets it down.
 *
 * A carried crab cannot be killed, and this is how long that protection
 * outlasts the carrying. Without it the wave does not kill the player, it
 * arranges for the beach to — which is a death they had no input into and the
 * one thing "carries rather than kills" cannot be allowed to mean.
 *
 * It also stops a crab landing in washing surf from being picked straight back
 * up, so a set costs a lane rather than an unbroken ride to the tide line.
 */
export const SURF_GRACE_TICKS = 30;

/** Narrowest and widest a drifting hazard can be. */
export const DRIFT_WIDTH = { min: 16, max: 34 } as const;

/**
 * Slowest and fastest a drifting lane can run, in board units per second.
 *
 * The ceiling stays well under {@link LATERAL_SPEED} so that a crab standing in
 * a gap can always track it rather than being carried out of it.
 */
export const DRIFT_SPEED = { min: 9, max: 24 } as const;

/** Fewest and most hazards in a drifting lane. */
export const DRIFT_COUNT = { min: 2, max: 3 } as const;

/** Narrowest and widest a static blocker can be. */
export const STILL_WIDTH = { min: 10, max: 26 } as const;

/** Fewest and most blockers in a static lane. */
export const STILL_COUNT = { min: 2, max: 2 } as const;

/** Proportion of hazard lanes that are static blockers rather than drifting. */
export const STILL_LANE_CHANCE = 0.3;

/**
 * Ticks between one seagull dive and the next, and how the dive is divided.
 *
 * The bird locks onto wherever the crab is standing, darkens that patch of
 * sand while it circles, and then hits it. `SEAGULL_WARN_TICKS` is the lead
 * time the parent spec's acceptance criterion is about: long enough that an
 * alert player moves out of it, and it is a named constant precisely so that a
 * later polish pass cannot quietly shorten the warning by adjusting a curve.
 */
export const SEAGULL_PERIOD_TICKS = 620;

/** Ticks the shadow grows on the sand before the bird arrives. */
export const SEAGULL_WARN_TICKS = 96;

/** Ticks the strike itself is lethal, once the warning has run out. */
export const SEAGULL_STRIKE_TICKS = 22;

/** Half the width of the patch a seagull strike covers, in board units. */
export const SEAGULL_HALF_W = 8;

/**
 * Ticks between frisbee throws, and how long one is in the air.
 *
 * A frisbee crosses the board rather than patrolling a lane, and it is in the
 * air for a good deal less than the gap between throws — it is an interruption
 * to be waited out, not a second set of lanes to solve.
 */
export const FRISBEE_PERIOD_TICKS = 540;

/** Ticks a frisbee spends crossing the board. */
export const FRISBEE_FLIGHT_TICKS = 150;

/** Half the width and half the height of a frisbee's box, in board units. */
export const FRISBEE_HALF = { width: 5, height: 4 } as const;

/**
 * How many lanes a frisbee rises and falls across its flight.
 *
 * The parent spec calls it a hazard that "arcs across two lanes at once", which
 * is what this is: its centre travels a full lane up the beach and back down
 * again, so at any moment it overlaps two rows and the pair it overlaps changes
 * as it flies.
 */
export const FRISBEE_ARC_LANES = 1;

/** Proportion of still lanes where one blocker is an umbrella that plants. */
export const UMBRELLA_CHANCE = 0.35;

/**
 * The window, in run ticks, within which an umbrella plants itself.
 *
 * Spread across most of a run so the beach keeps changing behind and ahead of
 * the player rather than all at once. The earliest is well after the opening:
 * a lane that gained a hazard while the player was still learning the controls
 * would read as the game moving the goalposts rather than as the beach filling
 * up.
 */
export const UMBRELLA_PLANTS = { earliest: 420, latest: 2_700 } as const;

/**
 * Ticks an umbrella spends visibly arriving before it is lethal.
 *
 * The spec's obligation for this hazard: a thing that was not lethal a moment
 * ago and now is needs a moment the player can see, rather than appearing
 * between one frame and the next. Comfortably longer than a forward step, so a
 * player already committed to the lane can still land and move clear.
 */
export const UMBRELLA_PLANT_TICKS = 45;

/**
 * Proportion of hazard lanes that hide a shell.
 *
 * Around seven on a beach, which is enough that a collected count is a real
 * second axis and few enough that each one is a decision rather than a chore.
 */
export const SHELL_CHANCE = 0.4;

/** Half the width of a shell, in board units. */
export const SHELL_HALF_W = 3;

/**
 * How far a shell sits from the centre of its gap, as a fraction of the room
 * either side of it.
 *
 * Zero would put every shell dead centre, which is exactly where a player
 * crossing the gap already is — the pickup would be free and therefore not a
 * decision. Offsetting it toward one edge means taking it costs a moment of
 * lining up against a hazard's edge, which is the risk the shell is meant to
 * be paid for with.
 *
 * It stays a fraction of the *available* room rather than a fixed distance, so
 * the offset can never push a shell into a hazard however narrow its gap is.
 */
export const SHELL_GAP_BIAS = 0.55;

/**
 * Ticks in one full stride of the crab's legs.
 *
 * Animation phase is derived from the tick and nothing else — never from a
 * private counter or a frame delta — so two devices drawing the same tick draw
 * the same crab. Twenty ticks is a third of a second, which reads as scurrying
 * without turning into a blur at the scale the legs are actually drawn.
 */
export const GAIT_TICKS = 20;

/**
 * How far a leg swings, as a fraction of the crab's half-height.
 *
 * Scaled by how fast the crab is actually moving, so a standing crab shuffles
 * and a running one strides. Purely cosmetic: the collision box never changes.
 */
export const GAIT_SWING = 0.5;

/**
 * Board units of lateral speed at which the leg swing reaches full amplitude.
 *
 * Set below {@link LATERAL_SPEED} so that ordinary movement looks committed
 * rather than tentative.
 */
export const GAIT_FULL_SPEED = LATERAL_SPEED * 0.6;

/**
 * Board units of drifting hazard per beachgoer.
 *
 * A drifting hazard is up to thirty-four units wide, which is far too wide to
 * read as one person. It is drawn as a group of walkers spaced across the whole
 * hazard instead, which fills the collision box honestly — art that is narrower
 * than the box it kills you from is art that reads as the game cheating.
 *
 * Tight enough that a group reads as a crowd rather than as individuals with
 * crossable daylight between them. The shadow beneath carries the true extent,
 * but the figures should not be arguing with it.
 */
export const WALKER_SPACING = 8;

/** Ticks in one full stride of a walking beachgoer. */
export const WALKER_GAIT_TICKS = 34;

/** Board units of towel per stripe. */
export const TOWEL_STRIPE_SPACING = 7;

/**
 * Milliseconds of vibration when a forward step commits.
 *
 * The game is about a decision that cannot be taken back, and on a phone a
 * physical thump says so more directly than the colour change does. Short
 * enough to read as a tap rather than a buzz — anything longer stops feeling
 * like the moment of commitment and starts feeling like a notification.
 *
 * Not supported by Safari on iOS, where this does nothing at all.
 */
export const STEP_HAPTIC_MS = 18;
